// <auto-generated />
using System;
using DataAccessLayer.DatabaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(EventDataContext))]
    [Migration("20201203141918_SeedDataModel")]
    partial class SeedDataModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataAccessLayer.DatabaseModels.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("EventID");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            CommentID = 1,
                            Comments = "Nice Event...!",
                            DateTime = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 1
                        },
                        new
                        {
                            CommentID = 2,
                            Comments = "I like it...!",
                            DateTime = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 1
                        },
                        new
                        {
                            CommentID = 3,
                            Comments = "Superb Event",
                            DateTime = new DateTime(2020, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 2
                        },
                        new
                        {
                            CommentID = 4,
                            Comments = "Great...",
                            DateTime = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 2
                        },
                        new
                        {
                            CommentID = 5,
                            Comments = "Nice",
                            DateTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 2
                        },
                        new
                        {
                            CommentID = 6,
                            Comments = "Thanks for it.",
                            DateTime = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 1
                        },
                        new
                        {
                            CommentID = 7,
                            Comments = "Gazab..(`.`)",
                            DateTime = new DateTime(2019, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 5
                        },
                        new
                        {
                            CommentID = 8,
                            Comments = "Cool Event",
                            DateTime = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 5
                        },
                        new
                        {
                            CommentID = 9,
                            Comments = "You are Great",
                            DateTime = new DateTime(2019, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 8
                        },
                        new
                        {
                            CommentID = 10,
                            Comments = "Waiting for it...",
                            DateTime = new DateTime(2020, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 6
                        },
                        new
                        {
                            CommentID = 11,
                            Comments = "Super cool",
                            DateTime = new DateTime(2020, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 9
                        },
                        new
                        {
                            CommentID = 12,
                            Comments = "Nice Event...!",
                            DateTime = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 8
                        },
                        new
                        {
                            CommentID = 13,
                            Comments = "Very interesting",
                            DateTime = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 8
                        },
                        new
                        {
                            CommentID = 14,
                            Comments = "Nice Event...!",
                            DateTime = new DateTime(2019, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 9
                        },
                        new
                        {
                            CommentID = 15,
                            Comments = "Cool",
                            DateTime = new DateTime(2018, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventID = 9
                        });
                });

            modelBuilder.Entity("DataAccessLayer.DatabaseModels.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("int");

                    b.Property<string>("InviteByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            Date = new DateTime(2020, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 1,
                            InviteByEmail = "laura@gmail.com",
                            Location = "India",
                            OtherDetails = "",
                            StartTime = "09:00",
                            Title = "Node Js",
                            Type = "Public",
                            UserID = 1
                        },
                        new
                        {
                            EventID = 2,
                            Date = new DateTime(2017, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 2,
                            InviteByEmail = "yanli@rediff.com,arturo@yahoo.com",
                            Location = "America",
                            OtherDetails = "",
                            StartTime = "12:00",
                            Title = "Java Quiz",
                            Type = "Public",
                            UserID = 1
                        },
                        new
                        {
                            EventID = 3,
                            Date = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 2,
                            InviteByEmail = "carson@gmail.com,anmol.baroliya@nagarro.com",
                            Location = "New Delhi",
                            OtherDetails = "",
                            StartTime = "08:00",
                            Title = "Level Up",
                            Type = "Private",
                            UserID = 2
                        },
                        new
                        {
                            EventID = 4,
                            Date = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 2,
                            InviteByEmail = "",
                            Location = "London",
                            OtherDetails = "",
                            StartTime = "11:00",
                            Title = "Altered Images",
                            Type = "Public",
                            UserID = 2
                        },
                        new
                        {
                            EventID = 5,
                            Date = new DateTime(2019, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 4,
                            InviteByEmail = "arturo@yahoo.com",
                            Location = "Germany",
                            OtherDetails = "",
                            StartTime = "10:00",
                            Title = "Josh Clapham Memorial Show",
                            Type = "Private",
                            UserID = 3
                        },
                        new
                        {
                            EventID = 6,
                            Date = new DateTime(2020, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 3,
                            InviteByEmail = "yanli@rediff.com",
                            Location = "New York",
                            OtherDetails = "",
                            StartTime = "16:00",
                            Title = "The Doors Alive",
                            Type = "Private",
                            UserID = 8
                        },
                        new
                        {
                            EventID = 7,
                            Date = new DateTime(2021, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 4,
                            InviteByEmail = "",
                            Location = "Sydeny,Australia",
                            OtherDetails = "",
                            StartTime = "18:00",
                            Title = "Easter Concert",
                            Type = "Private",
                            UserID = 3
                        },
                        new
                        {
                            EventID = 8,
                            Date = new DateTime(2019, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 1,
                            InviteByEmail = "anmol.baroliya@nagarro.com",
                            Location = "Delhi",
                            OtherDetails = "",
                            StartTime = "13:00",
                            Title = "Mental Health Conference",
                            Type = "Public",
                            UserID = 3
                        },
                        new
                        {
                            EventID = 9,
                            Date = new DateTime(2017, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 3,
                            InviteByEmail = "nino.olivetto@gmail.com",
                            Location = "Texas,USA",
                            OtherDetails = "",
                            StartTime = "01:00",
                            Title = "Propaganda Live Tour",
                            Type = "Private",
                            UserID = 4
                        },
                        new
                        {
                            EventID = 10,
                            Date = new DateTime(2021, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "We’ve received demand to host online workshop.",
                            DurationInHours = 1,
                            InviteByEmail = "",
                            Location = "California",
                            OtherDetails = "In response to this demand, A.I. For Anyone is excited to host a Learn AI in 60 Minutes virtual workshop in partnership with the Mark Cuban Foundation.",
                            StartTime = "06:00",
                            Title = "Learn AI In 60 Minutes",
                            Type = "Public",
                            UserID = 8
                        },
                        new
                        {
                            EventID = 11,
                            Date = new DateTime(2020, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 1,
                            InviteByEmail = "laura@gmail.com,anmol.baroliya@nagarro.com",
                            Location = "Mumbai",
                            OtherDetails = "",
                            StartTime = "04:00",
                            Title = "Learn Python",
                            Type = "Public",
                            UserID = 7
                        },
                        new
                        {
                            EventID = 12,
                            Date = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 4,
                            InviteByEmail = "yanli@rediff.com,arturo@yahoo.com",
                            Location = "Gurgaon",
                            OtherDetails = "",
                            StartTime = "05:00",
                            Title = "Tech Fest",
                            Type = "Public",
                            UserID = 7
                        },
                        new
                        {
                            EventID = 13,
                            Date = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 3,
                            InviteByEmail = "carson@gmail.com",
                            Location = "New Delhi",
                            OtherDetails = "",
                            StartTime = "08:00",
                            Title = "Online Quiz",
                            Type = "Private",
                            UserID = 8
                        },
                        new
                        {
                            EventID = 14,
                            Date = new DateTime(2016, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 2,
                            InviteByEmail = "",
                            Location = "Ghaziabad",
                            OtherDetails = "",
                            StartTime = "14:00",
                            Title = "Year Book",
                            Type = "Public",
                            UserID = 8
                        },
                        new
                        {
                            EventID = 15,
                            Date = new DateTime(2015, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationInHours = 4,
                            InviteByEmail = "arturo@yahoo.com,anmol.baroliya@nagarro.com",
                            Location = "Shahdara",
                            OtherDetails = "",
                            StartTime = "21:00",
                            Title = "Memorial Show",
                            Type = "Private",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("DataAccessLayer.DatabaseModels.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "carson@gmail.com",
                            FullName = "Carson Alexander",
                            Password = "carson@"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "meredith@gmail.com",
                            FullName = "Meredith Alonso",
                            Password = "meredith!"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "arturo@yahoo.com",
                            FullName = "Arturo Anand",
                            Password = "arturo@"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "yanli@rediff.com",
                            FullName = "Yan Li",
                            Password = "yanli#"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "peggy@gmail.com",
                            FullName = "Peggy Justice",
                            Password = "peggy!"
                        },
                        new
                        {
                            UserID = 6,
                            Email = "nino.olivetto@gmail.com",
                            FullName = "Nino Olivetto",
                            Password = "nino@!"
                        },
                        new
                        {
                            UserID = 7,
                            Email = "laura@gmail.com",
                            FullName = "Laura Norman",
                            Password = "laura@"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.DatabaseModels.Comment", b =>
                {
                    b.HasOne("DataAccessLayer.DatabaseModels.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DataAccessLayer.DatabaseModels.Event", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
